### ISSUE TITLE
Error in node.js

### ISSUE THREAD

**Issue by ysilvela** [danialfarid/ng-file-upload#1149]
When I upload a file I obtain this error in the node.js server:

PUT /api/tptalent/account/56013e691be0e0670d000001 200 12.925 ms - 1229
ReferenceError: _ is not defined
    at uploadFile (/var/lib/openshift/55c498422d52715e590000a8/app-root/runtime/repo/api/routesTPTalent.js:794:17)
    at callbacks (/var/lib/openshift/55c498422d52715e590000a8/app-root/runtime/repo/node_modules/express/lib/router/index.js:164:37)
    at param (/var/lib/openshift/55c498422d52715e590000a8/app-root/runtime/repo/node_modules/express/lib/router/index.js:138:11)

This line in the code is :
var data = _.pick(req.body, 'type')

Thanks

**Comment by danialfarid** [comment]
This plugin is a client side library. For node.js questions post it on stackoverflow or nodejs issues.
