### ISSUE TITLE
Angular 1.4.9

### ISSUE THREAD

**Issue by carlos-** [danialfarid/ng-file-upload#1309]
I have an exception after selecting a file (Chrome v.47), this error on console only happens after upgrading **Angular to 1.4.9** from 1.4.8. Is this happening to you? 

```
Error: [$compile:nonassign] Expression 'undefined' used with directive 'afpFileUpload' is non-assignable!
http://errors.angularjs.org/1.4.9/$compile/nonassign?p0=undefined&p1=afpFileUpload
    at http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:10628:13
    at parentSet (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:19652:22)
    at parentValueWatch (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:19665:20)
    at Object.regularInterceptedExpression (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:25206:17)
    at Scope.$digest (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:26647:41)
    at Scope.$apply (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:26919:25)
    at $$debounceViewValueCommit (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:36370:15)
    at $setViewValue (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:36342:13)
    at n (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:102652:7456)
    at http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:102652:8229 undefined(anonymous function) @ app.js:23282(anonymous function) @ app.js:20050(anonymous function) @ app.js:56542Scope.$digest @ app.js:26673Scope.$apply @ app.js:26919$$debounceViewValueCommit @ app.js:36370$setViewValue @ app.js:36342n @ app.js:102652(anonymous function) @ app.js:102652(anonymous function) @ app.js:28692completeOutstandingRequest @ app.js:16289(anonymous function) @ app.js:16566
app.js:23282 Error: [$compile:nonassign] Expression 'undefined' used with directive 'afpFileUpload' is non-assignable!
http://errors.angularjs.org/1.4.9/$compile/nonassign?p0=undefined&p1=afpFileUpload
    at http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:10628:13
    at parentSet (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:19652:22)
    at parentValueWatch (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:19665:20)
    at Object.regularInterceptedExpression (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:25206:17)
    at Scope.$digest (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:26647:41)
    at Scope.$apply (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:26919:25)
    at http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:28701:37
    at completeOutstandingRequest (http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:16289:11)
    at http://tuxdmzdevt01.dmz.avaloq.com/jenkins/view/AFP-JS/job/afp-js-showcase/1310/Showcase/app.js:16566:8 undefined(anonymous function) @ app.js:23282(anonymous function) @ app.js:20050(anonymous function) @ app.js:56542Scope.$digest @ app.js:26673Scope.$apply @ app.js:26919(anonymous function) @ app.js:28701completeOutstandingRequest @ app.js:16289(anonymous function) @ app.js:16566
```

Downgrading Angular to 1.4.8 the error message disappears.

**Comment by danialfarid** [comment]
This is not related to this plugin.
