### ISSUE TITLE
Seems not support Anuglar 1.5

### ISSUE THREAD

**Issue by JimmyLv** [danialfarid/ng-file-upload#1365]
It works well when we use Angular 1.4.x, but broken after migrating to Angular 1.5, Cloud you please help to check this error and give some suggestion?

```js
TypeError: Cannot read property 'ngfCapture' of undefined
    at upload.getAttrWithDefaults (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:397:30)
    at upload.attrGetter (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:402:24)
    at attrGetter (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:690:21)
    at linkFileSelect (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:718:33)
    at link (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:894:7)
    at invokeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:9492:9)
    at nodeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:8978:11)
    at http://localhost:9000/selfservice/bower_components/angular/angular.js:9231:13
    at processQueue (http://localhost:9000/selfservice/bower_components/angular/angular.js:15552:28)
    at http://localhost:9000/selfservice/bower_components/angular/angular.js:15568:27 

<input id="fileInput" type="file" ngf-select="validateFile($file)" ngf-multiple="false" accept="{{properties['upload.document.types']}}" required="" ng-model="$parent.file" class="ng-pristine ng-untouched ng-valid">
```

```js
TypeError: Cannot read property 'attr' of undefined
    at ng-file-upload.js:716
    at Scope.$get.Scope.$digest (angular.js:16664)
    at Scope.$get.Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded (angular.js:11405)(anonymous function) @ angular.js:13236$get @ angular.js:9965$get.Scope.$digest @ angular.js:16682$get.Scope.$apply @ angular.js:16928done @ angular.js:11266completeRequest @ angular.js:11464requestLoaded @ angular.js:11405
angular.js:13236 

TypeError: Cannot read property 'dropAvailable' of undefined
    at upload.getAttrWithDefaults (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:397:30)
    at upload.attrGetter (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:402:24)
    at attrGetter (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:1765:21)
    at linkDrop (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:1768:9)
    at ngFileUpload.directive.link (http://localhost:9000/selfservice/bower_components/ng-file-upload/ng-file-upload.js:1736:11)
    at invokeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:9492:9)
    at nodeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:8978:11)
    at compositeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:8226:13)
    at compositeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:8229:13)
    at compositeLinkFn (http://localhost:9000/selfservice/bower_components/angular/angular.js:8229:13)
```

**Comment by JimmyLv** [comment]
Why ngfCapture oand dropAvailable? I did not use ngfCapture at all. Or anyone can give me any idea about these error messages? Thanks very much!

**Comment by raminv80** [comment]
No unfortunately it's not working on 1.5.x. Running http://jsfiddle.net/danialfarid/maqbzv15/544/ on Angular 1.5.x throws execptions "Cannot read property '$id' of undefined" during bootstrap.

**Comment by JimmyLv** [comment]
@raminv80 Have you fixed it or any idea?

**Comment by raminv80** [comment]
Not yet mate, I used an in house alternative for now but it is in my TODO list.

**Comment by danialfarid** [comment]
The jsfiddle and demo page work on 1.5.0. Just ignore the errors.

**Comment by hassanbazzi** [comment]
Uhh..... Can we not just ignore the errors?

**Comment by danialfarid** [comment]
There is no error in the jsfiddle and demo page that I am testing so it might be something in your code.
