### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by jib5920** [danialfarid/ng-file-upload#1616]
I am using version 12.0.4 within a mean stack app. 
I was initially having issues with angular recognizing the module and then realized that it was installed globally. After installing it locally I tried to run it with a require statement attached and I received this error in my shell:
C:\myapp\node_modules\ng-file-upload\dist\ng-file-upload-all.js:23
  if (!window.FileAPI) {
       ^

ReferenceError: window is not defined
    at C:\myapp\node_modules\ng-file-upload\dist\ng-file-upload-all.js:23:8
    at Object.<anonymous> (C:\myapp\node_modules\ng-file-upload\dist\ng-file-upload-all.js:230:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\myapp\node_modules\ng-file-upload\index.js:1:63)
    at Module._compile (module.js:409:26)

If there were other cited issues like this and I missed them, please link them!

**Comment by danialfarid** [comment]
You probably trying to run it server side.
