### ISSUE TITLE
TypeError: Illegal constructor

### ISSUE THREAD

**Issue by aldarund** [danialfarid/ng-file-upload#1620]
```
TypeError: Illegal constructor
  at [object Object].isResumeSupported(~/ng-file-upload/dist/ng-file-upload-all.js:454:0)
  at new <anonymous>(~/ng-file-upload/dist/ng-file-upload-all.js:457:0)
  at Object.instantiate(~/angular/angular.js:4724:0)
  at Object.<anonymous>(~/angular/angular.js:4564:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at ? (~/angular/angular.js:4508:0)
  at getService(~/angular/angular.js:4655:0)
  at injectionArgs(~/angular/angular.js:4679:0)
  at Object.instantiate(~/angular/angular.js:4721:0)
  at Object.<anonymous>(~/angular/angular.js:4564:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at ? (~/angular/angular.js:4508:0)
  at getService(~/angular/angular.js:4655:0)
  at injectionArgs(~/angular/angular.js:4679:0)
  at Object.instantiate(~/angular/angular.js:4721:0)
  at Object.<anonymous>(~/angular/angular.js:4564:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at ? (~/angular/angular.js:4508:0)
  at getService(~/angular/angular.js:4655:0)
  at injectionArgs(~/angular/angular.js:4679:0)
  at Object.instantiate(~/angular/angular.js:4721:0)
  at Object.<anonymous>(~/angular/angular.js:4564:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at ? (~/angular/angular.js:4508:0)
  at getService(~/angular/angular.js:4655:0)
  at injectionArgs(~/angular/angular.js:4679:0)
  at Object.instantiate(~/angular/angular.js:4721:0)
  at Object.<anonymous>(~/angular/angular.js:4564:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at ? (~/angular/angular.js:4508:0)
  at getService(~/angular/angular.js:4655:0)
  at injectionArgs(~/angular/angular.js:4679:0)
  at Object.invoke(~/angular/angular.js:4701:0)
  at ? (~/angular/angular.js:7668:0)
  at forEach(~/angular/angular.js:321:0)
  at Object.<anonymous>(~/angular/angular.js:7666:0)
  at Object.invoke(~/angular/angular.js:4709:0)
  at Object.enforcedReturnValue [as $get](~/angular/angular.js:4548:0)
  at Object.invoke(~/angular/angular.js:4709:0)
```
happens on this line https://github.com/danialfarid/ng-file-upload/blob/master/src/upload.js#L33 
on android 4.x and 3.x

**Comment by danialfarid** [comment]
Should be fixed in later versions.
