### ISSUE TITLE
Crashes under random circumstances in Chrome

### ISSUE THREAD

**Issue by rocifier** [danialfarid/ng-file-upload#1641]
My Chrome browser (latest version on windows 10) broke ng-file-upload with the following exception and html code before even uploading a file (uploading didnt work either). My friend's computer which had the exact same code and Chrome version but Windows 7 didn't cause the exception. Both computers with Windows 10 or Edge or Firefox worked, I could only reproduce this on my setup:

    angular.js:13295 TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (<anonymous>:703:19)
    at Scope.$delegate.__proto__.$watch (<anonymous>:735:28)
    at linkFileSelect (http://emblim.localhost/resources/js/libs/ng-file-upload.js:731:26)
    at link (http://emblim.localhost/resources/js/libs/ng-file-upload.js:910:7)
    at invokeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:9526:23)
    at nodeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:8933:27)
    at compositeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:8261:31)
    at compositeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:8264:31)
    at nodeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:8928:38)
    at compositeLinkFn (http://emblim.localhost/resources/js/libs/prerequisites/angular.js:8261:31) 

    <input type="file" class="form-control form-control-file ng-pristine ng-untouched ng-valid" ngf-select="" ng-model="ACECtrl.eventImage" name="eventImage" ngf-max-size="2MB" ngf-pattern=".jpg,.png,.jpeg" ngf-model-invalid="errorBannerFile">

However reading the code, it seems that this should be patched for everyone, because they may not be using the below attributes. Adding these if statements around attribute getters from lines 730 fixed the issue. Sorry we are working to time/budget and I don't have time to submit a diff or search the issues page to see if this is an existing issue:

        var unwatches = [];
        if (attrGetter('ngfMultiple')) {
            unwatches.push(scope.$watch(attrGetter('ngfMultiple'), function () {
                fileElem.attr('multiple', attrGetter('ngfMultiple', scope));
            }));
        }
        if (attrGetter('ngfCapture')) {
            unwatches.push(scope.$watch(attrGetter('ngfCapture'), function () {
                fileElem.attr('capture', attrGetter('ngfCapture', scope));
            }));
        }
        if (attrGetter('ngfAccept')) {
            unwatches.push(scope.$watch(attrGetter('ngfAccept'), function () {
                fileElem.attr('accept', attrGetter('ngfAccept', scope));
            }));
        }

**Comment by chux0519** [comment]
thanks a lot the same issue

**Comment by rocifier** [comment]
Nice can you do a PR to original repositories?
