### ISSUE TITLE
Problem with Angular 1.3.14

### ISSUE THREAD

**Issue by mrtonyhuynh** [danialfarid/ng-file-upload#620]
# Module:
```javascript
angular.module('myapp', ['ngAnimate', 'ngCookies', 'ngTouch', 'ngSanitize', 'ngResource', 'ui.router', 'ui.bootstrap', 'textAngular', 'uiGmapgoogle-maps', 'angularFileUpload'])
..
```

# Controller:
```javascript
angular.module('myapp')
  .controller('BusinessGalleryCtrl', function ($scope, $upload) {
    $scope.$watch('files', function () {
        $scope.upload($scope.files);
    });
    $scope.upload = function (files) { 
        if (files && files.length) {
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                $upload.upload({
                    url: 'upload/url',
                    fields: {'username': $scope.username},
                    file: file
                }).progress(function (evt) {
                    var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                    console.log('progress: ' + progressPercentage + '% ' + evt.config.file.name);
                }).success(function (data, status, headers, config) {
                    console.log('file ' + config.file.name + 'uploaded. Response: ' + data);
                });
            }
        }
    };
  });
```

# HTML
```
...
<div class="col-sm-3 col-md-2">
        <div ng-file-drop ng-model="files" class="thumbnail upload drop-box" drag-over-class="dragover" ng-multiple="true" allow-dir="true" accept=".jpg,.png,.pdf">Drop Images or
            <div class="button" ng-file-select ng-file-change="upload($files)">select file</div>
        </div>
        <div ng-no-file-drop>File Drag/Drop is not supported for this browser</div>
    </div>
...
```

# Error:
```
Error: [$injector:unpr] Unknown provider: $uploadProvider <- $upload <- BusinessGalleryCtrl
http://errors.angularjs.org/1.3.14/$injector/unpr?p0=%24uploadProvider%20%3C-%20%24upload%20%3C-%20BusinessGalleryCtrl
    at REGEX_STRING_REGEXP (http://localhost:3000/bower_components/angular/angular.js:63:12)
    at http://localhost:3000/bower_components/angular/angular.js:3997:19
    at Object.getService [as get] (http://localhost:3000/bower_components/angular/angular.js:4144:39)
    at http://localhost:3000/bower_components/angular/angular.js:4002:45
    at getService (http://localhost:3000/bower_components/angular/angular.js:4144:39)
    at invoke (http://localhost:3000/bower_components/angular/angular.js:4176:13)
    at Object.instantiate (http://localhost:3000/bower_components/angular/angular.js:4193:27)
    at http://localhost:3000/bower_components/angular/angular.js:8462:28
    at compile (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3897:28)
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8219:9) <div ui-view="" class="ng-scope">
```

**Comment by danialfarid** [comment]
That doesn't seem to be related to angular version.
The demo page works with angular 1.3.14:
http://angular-file-upload.appspot.com/#/1.3.14

**Comment by collinszac10** [comment]
I'm getting a very similar error.  I only get the error when I try to inject the $upload directive into my service.  I've referenced both scripts required.
```
Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=%24uploadProvider%20%3C-%20%24upload%20%3C-%20recipesService
M/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:6:417
ab/p.$injector<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:38:7
d@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:13
ab/t.$injector<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:38:79
d@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:13
e@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:283
e/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:34:266
e@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:313
ab/t.$injector<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:38:108
d@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:13
e@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:283
h/<.instantiate@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:432
Fe/this.$get</<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:76:3
A/<.link@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js:7:268
Z@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:70:149
A@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:203
g@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299
F/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:50:415
I/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:52:283
l@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:56:293
x@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js:6:364
Pe/this.$get</l.prototype.$broadcast@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:128:120
n/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js:11:426
f/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:112:20
Pe/this.$get</l.prototype.$eval@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:125:301
Pe/this.$get</l.prototype.$digest@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:122:390
Pe/this.$get</l.prototype.$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:56
l@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:81:169
S@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:85:301
vf/</D.onload@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:86:315

<div class="row ng-scope" data-ng-view="">
```

Service:
```
'use strict';
app.factory('recipesService', ['$http', 'ngAuthSettings','$upload', function ($http, ngAuthSettings, $upload) {

    var serviceBase = ngAuthSettings.apiServiceBaseUri;

    var recipesServiceFactory = {};

    var _getRecipes = function () {
        return $http.get(serviceBase + 'api/recipes').then(function (results) {

            return results;
        });
    };

    var _getNewRecipe = function () {
        return $http.get(serviceBase + "api/recipes/GetNewRecipe").then(function (results) {
            return results;
        });
    }

    recipesServiceFactory.getRecipes = _getRecipes;
    recipesServiceFactory.getNewRecipe = _getNewRecipe;

    return recipesServiceFactory;

}]);
```
