### ISSUE TITLE
Parse error when using img with ngfSrc directive

### ISSUE THREAD

**Issue by aderowbotham** [danialfarid/ng-file-upload#752]
Copying the simple example from your readme.md, I am trying to display an image thumbnail:

`<img ngf-src="files[0]" ngf-default-src="/thumb.jpg" ngf-accept="image/*">`

The directive is picking this up as I can log that its `link` function is triggered, but as soon as I try to upload a file I get an error:
`
Error: [$parse:syntax] http://errors.angularjs.org/1.3.15/$parse/syntax?p0=*&p1=not%20a%20primary%20expression&p2=7&p3=image%2F*&p4=*
    at Error (native)
    at http://dev.local/vendor_dev/angular/angular.min.js:6:417
    at ib.throwError (http://dev.local/vendor_dev/angular/angular.min.js:191:165)
    at ib.primary (http://dev.local/vendor_dev/angular/angular.min.js:190:419)
    at ib.unary (http://dev.local/vendor_dev/angular/angular.min.js:197:478)
    at ib.multiplicative (http://dev.local/vendor_dev/angular/angular.min.js:197:273)
    at ib.additive (http://dev.local/vendor_dev/angular/angular.min.js:197:63)
    at ib.relational (http://dev.local/vendor_dev/angular/angular.min.js:196:435)
    at ib.equality (http://dev.local/vendor_dev/angular/angular.min.js:196:291)
    at ib.logicalAND (http://dev.local/vendor_dev/angular/angular.min.js:196:167)
`

This error does not occur if I remove the thumbnail image tag.

I am using the `ngf-drop ` area only:

    <div 
        ngf-drop 
        ng-model="files" 
        class="drop-box" 
        ngf-drag-over-class="{ accept:'dragover', reject:'dragover-err', delay:100}" 
        ngf-multiple="true" 
        ngf-allow-dir="false"
        ngf-accept="'.jpg,.png'"
        ngf-max-size="10000000">Drag images here</div>
        <div ngf-no-file-drop>File Drag/Drop is not supported for this browser</div>

    <img ngf-src="files[0]" ngf-default-src="/thumb.jpg" ngf-accept="image/*">

**Comment by danialfarid** [comment]
`ngf-default-src="'/thumb.jpg'"`

**Comment by aderowbotham** [comment]
Ah, of course. Thanks!
