### ISSUE TITLE
I can't install the module by bower

### ISSUE THREAD

**Issue by amicos** [danialfarid/ng-file-upload#801]
This is my issue. I think perhaps that is the access problem. How i can specify the proxy. Thanks

bower retry         Download of https://github.com/danialfarid/angular-file-upload bower/archive/4.2.4.tar.gz failed with EAI_AGAIN, trying with git..
bower EPERM         EPERM, unlink 'C:\Users\****\AppData\Local\Temp\ADJCDFRAN
CE-****\bower\ng-file-upload-3476-DV1Gi4\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\******\AppData\Local\Temp\ADJCDFRANCE-*****\bo
wer\ng-file-upload-3476-DV1Gi4\archive.tar.gz'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\*****\AppData\Roaming\npm\node_modules
\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\******\AppData\Roaming\npm\node_modules\bow
er\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\*****\AppData\Roaming\npm\node_modules\bower\node
_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\*******\AppData\Roaming\npm\node_modules\bower\lib\commands\inde
x.js:45:20
    at _rejected (C:\Users\******\AppData\Roaming\npm\node_modules\bower\node_m
odules\q\q.js:844:24)
    at C:\Users\******\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.
js:870:30
    at Promise.when (C:\Users\*****\AppData\Roaming\npm\node_modules\bower\nod
e_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\******\AppData\Roaming\npm\nod
e_modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\******\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.
js:604:44

**Comment by amicos** [comment]
the real problem I have is that the karma task give me errors after I add ngUploadFile Module in bower.json. What I must do?
That is my issue:

            at C:/workspace/MyProject/src/main/webapp/bower_components/angular/angular.js:4139
            at forEach (C:/workspace/MyProject/src/main/webapp/bower_components/angular/angular.js:323)
            at loadModules (C:/workspace/MyProject/src/main/webapp/bower_components/angular/angular.js:4141)
            at createInjector (C:/workspace/JcdstreamIhm/src/main/webapp/bower_components/angular/angular.js:4025)
            at workFn (C:/workspace/JcdstreamIhm/src/main/webapp/bower_components/angular-mocks/angular-mocks.js:2425)
        TypeError: 'undefined' is not an object (evaluating 'scope.awesomeThings')
            at C:/workspace/MyProject/src/main/webapp/test/spec/controllers/main.js:20
PhantomJS 1.9.8 (Windows 7): Executed 2 of 2 (2 FAILED) ERROR (0.305 secs / 0.01 secs)
Warning: Task "karma:unit" failed. Use --force to continue.
Aborted due to warnings.

**Comment by danialfarid** [comment]
The module is called ngFileUpload not ngUploadFile and from the error log it doesn't seem like related to this plugin.

**Comment by amicos** [comment]
I add   "ng-file-upload" : "4.2.4" to bower.json file

I ask to install : bower install

Then I have this issue


Console trace: 

Error at StandardRenderer.error (C:\Users\me\AppData\Roaming\npm\node_modules
\bower\lib\renderers\StandardRenderer.js:82:37)
at Logger.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\bow
er\bin\bower:110:22)
at Logger.emit (events.js:107:17)
at Logger.emit (C:\Users\me\AppData\Roaming\npm\node_modules\bower\node
_modules\bower-logger\lib\Logger.js:29:39) 
at C:\Users\me\AppData\Roaming\npm\node_modules\bower\lib\commands\inde
x.js:45:20 at _rejected (C:\Users\me\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
at C:\Users\me\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30 at Promise.when (C:\Users\me\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
at Promise.promise.promiseDispatch (C:\Users\me\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
at C:\Users\me\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44

**Comment by amicos** [comment]
It was just a proxy problem 
thanks
