### ISSUE TITLE
file upload won't load in minified mode

### ISSUE THREAD

**Issue by akoskm** [danialfarid/ng-file-upload#856]
Hello and thanks for the great plugin!

My problem is that while in development mode everything works fine, after minification I'm getting the following error:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module account due to:
Error: [$injector:modulerr] Failed to instantiate module account.index due to:
Error: [$injector:modulerr] Failed to instantiate module ngFileUpload due to:
Error: [$injector:nomod] Module 'ngFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=ngFileUpload
    at http://localhost:3000/app.min.js:3:20639
    at http://localhost:3000/app.min.js:3:28985
    at b (http://localhost:3000/app.min.js:3:28557)
    at b (http://localhost:3000/app.min.js:3:28869)
    at http://localhost:3000/app.min.js:4:5343
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ngFileUpload&p1=Er…20%20%20%20at%20n%20(http%3A%2F%2Flocalhost%3A3000%2Fapp.min.js%3A4%3A5121)
    at http://localhost:3000/app.min.js:3:20639
    at http://localhost:3000/app.min.js:4:5549
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=account.index&p1=E…20%20%20%20at%20n%20(http%3A%2F%2Flocalhost%3A3000%2Fapp.min.js%3A4%3A5121)
    at http://localhost:3000/app.min.js:3:20639
    at http://localhost:3000/app.min.js:4:5549
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=account&p1=Error%3…20%20%20%20at%20n%20(http%3A%2F%2Flocalhost%3A3000%2Fapp.min.js%3A4%3A5121)
    at http://localhost:3000/app.min.js:3:20639
    at http://localhost:3000/app.min.js:4:5549
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at http://localhost:3000/app.min.js:4:5290
    at f (http://localhost:3000/app.min.js:3:21024)
    at n (http://localhost:3000/app.min.js:4:5121)
    at Sa (http://localhost:3000/app.min.js:4:6811)
    at h (http://localhost:3000/app.min.js:3:26670)
    at _ (http://localhost:3000/app.min.js:3:26980)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=app&p1=Error%3A%20…0%20%20%20at%20_%20(http%3A%2F%2Flocalhost%3A3000%2Fapp.min.js%3A3%3A26980)
```

My dependencies are defined in this order:

```
<script type="text/javascript" src="/vendor/jquery.js"></script>
<script type="text/javascript" src="/vendor/angular.js"></script>
...
<script type="text/javascript" src="ng-file-upload-shim.js"></script>
<script type="text/javascript" src="ng-file-upload.js"></script>

<script type="text/javascript" src="/app.js"></script>
```

And according to the examples, I'm loading the library like this:

```
angular.module('account.index', ['ngRoute', 'security.authorization', 'ngFileUpload']);
angular.module('account.index').config(['$routeProvider', 'securityAuthorizationProvider', function($routeProvider, securityAuthorizationProvider){
...
}]);
```

**Comment by danialfarid** [comment]
Does it work with if you reference the minified version of the js files?

**Comment by akoskm** [comment]
No, it doesn't work with minified versions.

**Comment by akoskm** [comment]
I forgot to add the plugins' path to my `copy` grunt task, so it wasn't copied to the directory which is used to serve the static assets in production mode.

Sorry, I'm closing this.
